import {useEffect,useRef,useState} from 'react';
import {compileSketch} from '../simulator/compiler';
import type {Project,Snapshot} from '../types';
export function useSimulation(project:Project){
 const worker=useRef<Worker|null>(null),generation=useRef(0),compiler=useRef<AbortController|null>(null);const [status,setStatus]=useState<'stopped'|'compiling'|'running'|'paused'>('stopped'),[snapshot,setSnapshot]=useState<Snapshot>({time:0,pins:{},states:{},serial:'',warnings:[]}),[serial,setSerial]=useState(''),[logs,setLogs]=useState('Ready. Compile an Uno sketch or import Intel HEX.'),[hex,setHex]=useState('');
 useEffect(()=>{const w=new Worker(new URL('../simulator/worker.ts',import.meta.url),{type:'module'});worker.current=w;w.onmessage=e=>{if(e.data.type==='snapshot'){setSnapshot(e.data.snapshot);if(e.data.snapshot.serial)setSerial(s=>(s+e.data.snapshot.serial).slice(-100000));}else {setLogs('Simulation stopped because an error occurred.\n'+e.data.message);setStatus('stopped');console.error(e.data.message);}};w.onerror=e=>{setLogs('Simulation stopped because an error occurred.\n'+e.message);setStatus('stopped');};return()=>{compiler.current?.abort();w.terminate();};},[]);
 useEffect(()=>{worker.current?.postMessage({type:'update',project});},[project]);
 function stop(){generation.current++;compiler.current?.abort();worker.current?.postMessage({type:'stop'});setStatus('stopped');setSnapshot({time:0,pins:{},states:{},serial:'',warnings:[]});}
 async function start(imported?:string){if(project.board!=='arduino-uno-r3'||project.components.filter(c=>c.type==='arduino-uno-r3').length!==1){setLogs('CPU emulation requires exactly one Arduino Uno R3. Other boards are Experimental.');return;}compiler.current?.abort();compiler.current=new AbortController();const token=++generation.current;setStatus('compiling');setLogs(imported?'Loading Intel HEX…':'Compiling locally with AVR GCC / WebAssembly…');try{const firmware=imported||await compileSketch(project.code,compiler.current.signal);if(token!==generation.current)return;setHex(firmware);setSerial('');worker.current?.postMessage({type:'start',hex:firmware,project});setStatus('running');setLogs('ATmega328P • 16 MHz • real AVR instructions.\n'+(imported?'Uploaded firmware loaded.':'Compilation successful.'));}catch(e){if(token!==generation.current)return;setStatus('stopped');setLogs(String(e));console.error(e);}}
 return {status,snapshot,serial,logs,hex,start,stop,pause:()=>{worker.current?.postMessage({type:status==='paused'?'resume':'pause'});setStatus(status==='paused'?'running':'paused');},clear:()=>setSerial(''),send:(text:string)=>worker.current?.postMessage({type:'serial',text}),setLogs};
}
