import {memo,useCallback} from 'react';
import {ReactFlow,Background,Controls,MiniMap,Handle,Position,ConnectionMode,applyNodeChanges,useReactFlow,type Connection,type NodeProps,type Node,type NodeChange} from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import {definitions} from '../components/registry';
import {PartVisual} from './PartVisual';
import {useProject} from '../store/useProject';
import type {Part,Snapshot} from '../types';
type PartNode=Node<{part:Part;state?:Snapshot['states'][string];press:(id:string,value:boolean)=>void},'part'>;
const ElectronicNode=memo(({data,selected}:NodeProps<PartNode>)=>{const {part,state}=data,d=definitions[part.type],isBoard=d.visual==='board';return <div className={`electronic-node ${isBoard?'board-node':''} ${selected?'selected':''}`} style={{transform:`rotate(${part.rotation}deg)`}}>
 <div className="node-name">{d.name}</div><PartVisual part={part} state={state}/>
 {d.visual==='button'&&<button className="physical-button nodrag" aria-label="Press button" onPointerDown={()=>data.press(part.id,true)} onPointerUp={()=>data.press(part.id,false)} onPointerLeave={()=>data.press(part.id,false)}/>}
 {d.pins.map((pin,i)=>{const right=isBoard?i>=2&&i<16:i%2===1,sidePins=d.pins.filter((_,j)=>isBoard?(right?j>=2&&j<16:!(j>=2&&j<16)):j%2===(right?1:0)),idx=sidePins.findIndex(x=>x.id===pin.id);const top=32+(idx+1)/(sidePins.length+1)*(isBoard?250:85);return <Handle key={pin.id} id={pin.id} type="source" position={right?Position.Right:Position.Left} style={{top,background:pin.type==='ground'?'#89929d':pin.type==='power'?'#d57d73':'#c2b58f'}}><span className={`pin-label ${right?'right':'left'}`}>{pin.id}</span></Handle>;})}
 <span className={`support ${d.supportLevel.toLowerCase()}`}>{d.supportLevel}</span>
 </div>;});
const nodeTypes={part:ElectronicNode};
export function Circuit({snapshot,select,selectedIds,color,report,add}:{snapshot:Snapshot;select:(ids:string[])=>void;selectedIds:string[];color:string;report:(s:string)=>void;add:(type:string,position?:{x:number;y:number})=>void}){
 const {project,edit}=useProject(),flow=useReactFlow();
 const press=useCallback((id:string,value:boolean)=>edit(p=>{p.components.find(c=>c.id===id)!.properties.pressed=value;},false),[edit]);
 const nodes:PartNode[]=project.components.map(part=>({id:part.id,type:'part',selected:selectedIds.includes(part.id),position:part.position,data:{part,state:snapshot.states[part.id],press}}));
 const onChange=(changes:NodeChange<PartNode>[])=>{const sels=changes.filter(c=>c.type==='select');if(sels.length){const ids=new Set(selectedIds);sels.forEach(c=>{if(c.type==='select'){if(c.selected)ids.add(c.id);else ids.delete(c.id);}});select([...ids]);}const positionChanges=changes.filter(c=>c.type==='position');if(positionChanges.length)edit(p=>{const next=applyNodeChanges(positionChanges,nodes);p.components.forEach(c=>{c.position=next.find(n=>n.id===c.id)?.position||c.position;});},false);};
 const connect=(c:Connection)=>{if(!c.sourceHandle||!c.targetHandle||c.source===c.target&&c.sourceHandle===c.targetHandle){report('Choose two different connection points.');return;}if(project.wires.some(w=>w.source===c.source&&w.target===c.target&&w.sourceHandle===c.sourceHandle&&w.targetHandle===c.targetHandle)){report('These pins are already connected.');return;}edit(p=>p.wires.push({...c,sourceHandle:c.sourceHandle!,targetHandle:c.targetHandle!,id:crypto.randomUUID(),color}));};
 return <div className="circuit-wrap" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const type=e.dataTransfer.getData('gubi/component');if(definitions[type])add(type,flow.screenToFlowPosition({x:e.clientX,y:e.clientY}));}}><ReactFlow nodes={nodes} edges={project.wires.map(w=>({...w,type:'smoothstep',style:{stroke:w.color,strokeWidth:2.5}}))} nodeTypes={nodeTypes} onNodesChange={onChange} onConnect={connect} onNodeDragStart={()=>edit(()=>{})} onEdgesDelete={edges=>edit(p=>{p.wires=p.wires.filter(w=>!edges.some(e=>e.id===w.id));})} onNodesDelete={nodes=>edit(p=>{const ids=nodes.map(n=>n.id);p.components=p.components.filter(c=>!ids.includes(c.id));p.wires=p.wires.filter(w=>!ids.includes(w.source)&&!ids.includes(w.target));})} connectionMode={ConnectionMode.Loose} snapToGrid snapGrid={[10,10]} selectionOnDrag panOnDrag={[1,2]} panActivationKeyCode="Space" multiSelectionKeyCode="Control" deleteKeyCode="Delete" fitView minZoom={.15} maxZoom={3} onNodeContextMenu={(e,n)=>{e.preventDefault();select([n.id]);report('Use the inspector to rotate, duplicate, or delete the selected part.');}}><Background color="#364049" gap={20} size={1}/><Controls/><MiniMap nodeColor="#457a72" maskColor="#11161acc"/></ReactFlow><div className="canvas-hint">Drag parts · connect pins · Space + drag to pan</div><div className="canvas-time">{snapshot.time.toFixed(2)} s · 16 MHz</div></div>;
}
